# Generated by Django 3.0.5 on 2020-05-08 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200507_0848'),
    ]

    operations = [
        migrations.AddField(
            model_name='frateuser',
            name='Email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='frateuser',
            name='Username',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
