# Generated by Django 3.0.5 on 2020-05-08 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200508_0942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frateuser',
            name='Email',
            field=models.EmailField(max_length=254),
        ),
    ]
