# Generated by Django 3.0.5 on 2020-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200620_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fratepost',
            name='Category',
            field=models.IntegerField(),
        ),
    ]
