# Generated by Django 3.0.5 on 2020-07-16 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200621_1242'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrateComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('comment', models.CharField(max_length=100)),
                ('postID', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='FrateFollower',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follower', models.CharField(max_length=50)),
                ('following', models.CharField(max_length=50)),
            ],
        ),
        migrations.RenameField(
            model_name='fratepost',
            old_name='Caption',
            new_name='caption',
        ),
        migrations.RenameField(
            model_name='fratepost',
            old_name='Category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='fratepost',
            old_name='Date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='fratepost',
            old_name='Filename',
            new_name='filename',
        ),
        migrations.RenameField(
            model_name='fratepost',
            old_name='Ratings',
            new_name='ratings',
        ),
        migrations.RenameField(
            model_name='fratepost',
            old_name='Username',
            new_name='username',
        ),
        migrations.RenameField(
            model_name='frateuser',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='frateuser',
            old_name='Password',
            new_name='password',
        ),
        migrations.RenameField(
            model_name='frateuser',
            old_name='Username',
            new_name='username',
        ),
    ]
