# Generated by Django 3.0.5 on 2020-07-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200716_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='fratepost',
            name='rateCount',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
