# Generated by Django 3.0.5 on 2020-07-19 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_fratepost_ratecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fratepost',
            name='rateCount',
            field=models.IntegerField(),
        ),
    ]
