# Generated by Django 3.0.5 on 2020-07-19 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_remove_fratepost_ratecount'),
    ]

    operations = [
        migrations.AddField(
            model_name='fratepost',
            name='rateCount',
            field=models.IntegerField(default=0),
        ),
    ]
