# Generated by Django 3.0.5 on 2020-07-19 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_fratepost_ratecount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fratepost',
            name='rateCount',
        ),
        migrations.AddField(
            model_name='fratepost',
            name='count',
            field=models.IntegerField(default=0),
        ),
    ]
